---
name: Release

on:
  push:
    branches: [main]

jobs:
  semrel:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: write
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: none
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Semantic Release
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true

      - name: Berg API docker meta
        id: berg-api-meta
        if: steps.semrel.outputs.version != ''
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/api
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}},value=${{ steps.semrel.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.semrel.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.semrel.outputs.version }}
          labels: |
            org.opencontainers.image.title=berg-api
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

      - name: Berg Frontend docker meta
        id: berg-frontend-meta
        if: steps.semrel.outputs.version != ''
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/frontend
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}},value=${{ steps.semrel.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.semrel.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.semrel.outputs.version }}
          labels: |
            org.opencontainers.image.title=berg-frontend
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

      - name: Login to GHCR
        if: steps.semrel.outputs.version != ''
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Berg API
        if: steps.semrel.outputs.version != ''
        id: berg-api-docker
        uses: docker/build-push-action@v7
        with:
          context: backend
          file: backend/Berg.Api/Dockerfile
          push: true
          tags: ${{ steps.berg-api-meta.outputs.tags }}
          build-args: |
            BERG_VERSION=${{ steps.semrel.outputs.version }}
          labels: |
            ${{ steps.berg-api-meta.outputs.labels }}

      - name: Build and push Berg Frontend
        if: steps.semrel.outputs.version != ''
        id: berg-frontend-docker
        uses: docker/build-push-action@v7
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: ${{ steps.berg-frontend-meta.outputs.tags }}
          labels: |
            ${{ steps.berg-frontend-meta.outputs.labels }}

      - name: Build and push Berg helm chart
        if: steps.semrel.outputs.version != ''
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: berg
          repository: bergctf/charts
          tag: ${{ steps.semrel.outputs.version }}
          app_version: ${{ steps.semrel.outputs.version }}
          path: charts/berg
          registry: ghcr.io
          registry_username: ${{ github.repository_owner }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
